"""Initial migration - patients

Revision ID: 6b5002443732
Revises: 
Create Date: 2025-11-20 00:16:17.118736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b5002443732'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_patient_history_created_at', 'patient_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_history_id'), 'patient_history', ['id'], unique=False)
    op.create_index(op.f('ix_patient_history_order_id'), 'patient_history', ['order_id'], unique=False)
    op.create_index('ix_patient_history_patient_id', 'patient_history', ['patient_id'], unique=False)
    op.create_table('patient_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_notes_id'), 'patient_notes', ['id'], unique=False)
    op.create_index('ix_patient_notes_patient_id', 'patient_notes', ['patient_id'], unique=False)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('DNI', 'RUC', name='documenttype', native_enum=False), nullable=False),
    sa.Column('document_number', sa.String(length=11), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_recurrent', sa.Boolean(), nullable=False),
    sa.Column('visit_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number')
    )
    op.create_index('ix_patients_document_number', 'patients', ['document_number'], unique=False)
    op.create_index('ix_patients_first_name_last_name', 'patients', ['first_name', 'last_name'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index('ix_patients_is_recurrent', 'patients', ['is_recurrent'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_patients_is_recurrent', table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index('ix_patients_first_name_last_name', table_name='patients')
    op.drop_index('ix_patients_document_number', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_patient_notes_patient_id', table_name='patient_notes')
    op.drop_index(op.f('ix_patient_notes_id'), table_name='patient_notes')
    op.drop_table('patient_notes')
    op.drop_index('ix_patient_history_patient_id', table_name='patient_history')
    op.drop_index(op.f('ix_patient_history_order_id'), table_name='patient_history')
    op.drop_index(op.f('ix_patient_history_id'), table_name='patient_history')
    op.drop_index('ix_patient_history_created_at', table_name='patient_history')
    op.drop_table('patient_history')
    # ### end Alembic commands ###
