FROM node:20-alpine

WORKDIR /app

# 1. Copia solo los archivos de dependencias para un caching eficiente
COPY package.json .
# COPY package-lock.json .

# 2. Instala las dependencias UNA VEZ. Esta capa se cacheará y reutilizará.
# El flag 'legacy' es para evitar conflictos en el entorno Alpine.
RUN npm install --legacy-peer-deps

# La imagen base está lista. El código fuente se montará vía VOLUME.