"""Add billing tables (invoices, invoice_items)

Revision ID: 4ca580e3efa7
Revises: d20d1fa9be35
Create Date: 2025-11-23 03:48:09.487158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ca580e3efa7'
down_revision: Union[str, None] = 'd20d1fa9be35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('location_id', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('customer_document_type', sa.String(length=10), nullable=False))
    op.add_column('invoices', sa.Column('customer_document_number', sa.String(length=11), nullable=False))
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=255), nullable=False))
    op.add_column('invoices', sa.Column('customer_address', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('invoices', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('invoices', 'issue_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_invoices_location_id'), 'invoices', ['location_id'], unique=False)
    op.create_index(op.f('ix_invoices_patient_id'), 'invoices', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_patient_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_location_id'), table_name='invoices')
    op.alter_column('invoices', 'issue_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_column('invoices', 'created_at')
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'customer_document_number')
    op.drop_column('invoices', 'customer_document_type')
    op.drop_column('invoices', 'location_id')
    op.drop_column('invoices', 'patient_id')
    # ### end Alembic commands ###
