"""Add service_code to invoice_items

Revision ID: 7f512d70be5c
Revises: 4ca580e3efa7
Create Date: 2025-12-08 20:36:50.023749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f512d70be5c'
down_revision: Union[str, None] = '4ca580e3efa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('service_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'service_code')
    # ### end Alembic commands ###
