"""Initial migration - billing, reconciliation

Revision ID: d20d1fa9be35
Revises: 
Create Date: 2025-11-20 00:55:18.943010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd20d1fa9be35'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_closures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('closure_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'REOPENED', name='closurestatus', native_enum=False), nullable=False),
    sa.Column('expected_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('registered_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_closures_closure_date'), 'daily_closures', ['closure_date'], unique=False)
    op.create_index(op.f('ix_daily_closures_id'), 'daily_closures', ['id'], unique=False)
    op.create_index(op.f('ix_daily_closures_location_id'), 'daily_closures', ['location_id'], unique=False)
    op.create_index(op.f('ix_daily_closures_status'), 'daily_closures', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('invoice_type', sa.Enum('BOLETA', 'FACTURA', name='invoicetype', native_enum=False), nullable=False),
    sa.Column('invoice_status', sa.Enum('DRAFT', 'PENDING', 'SENT', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invoicestatus', native_enum=False), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_invoice_status'), 'invoices', ['invoice_status'], unique=False)
    op.create_index(op.f('ix_invoices_issue_date'), 'invoices', ['issue_date'], unique=False)
    op.create_index(op.f('ix_invoices_order_id'), 'invoices', ['order_id'], unique=False)
    op.create_table('discrepancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closure_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['closure_id'], ['daily_closures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discrepancies_closure_id'), 'discrepancies', ['closure_id'], unique=False)
    op.create_index(op.f('ix_discrepancies_id'), 'discrepancies', ['id'], unique=False)
    op.create_index(op.f('ix_discrepancies_is_resolved'), 'discrepancies', ['is_resolved'], unique=False)
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_discrepancies_is_resolved'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_id'), table_name='discrepancies')
    op.drop_index(op.f('ix_discrepancies_closure_id'), table_name='discrepancies')
    op.drop_table('discrepancies')
    op.drop_index(op.f('ix_invoices_order_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_issue_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_daily_closures_status'), table_name='daily_closures')
    op.drop_index(op.f('ix_daily_closures_location_id'), table_name='daily_closures')
    op.drop_index(op.f('ix_daily_closures_id'), table_name='daily_closures')
    op.drop_index(op.f('ix_daily_closures_closure_date'), table_name='daily_closures')
    op.drop_table('daily_closures')
    # ### end Alembic commands ###
