"""add_missing_fields_to_invoice

Revision ID: d60a67c5c1c9
Revises: e213d680ca52
Create Date: 2025-12-09 17:39:42.408311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd60a67c5c1c9'
down_revision: Union[str, None] = 'e213d680ca52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
