"""add_customer_and_financial_fields_to_invoice

Revision ID: e213d680ca52
Revises: 7f512d70be5c
Create Date: 2025-12-09 17:20:14.297395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e213d680ca52'
down_revision: Union[str, None] = '7f512d70be5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('customer_document_type', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('customer_document_number', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('customer_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('customer_address', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True))

    op.execute("UPDATE invoices SET customer_document_type = '' WHERE customer_document_type IS NULL")
    op.execute("UPDATE invoices SET customer_document_number = '' WHERE customer_document_number IS NULL")
    op.execute("UPDATE invoices SET customer_name = '' WHERE customer_name IS NULL")
    op.execute("UPDATE invoices SET subtotal = 0 WHERE subtotal IS NULL")
    op.execute("UPDATE invoices SET tax = 0 WHERE tax IS NULL")

    op.alter_column('invoices', 'customer_document_type', nullable=False)
    op.alter_column('invoices', 'customer_document_number', nullable=False)
    op.alter_column('invoices', 'customer_name', nullable=False)
    op.alter_column('invoices', 'subtotal', nullable=False)
    op.alter_column('invoices', 'tax', nullable=False)

    op.add_column('invoice_items', sa.Column('service_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tax')
    op.drop_column('invoices', 'subtotal')
    op.drop_column('invoices', 'customer_address')
    op.drop_column('invoices', 'customer_name')
    op.drop_column('invoices', 'customer_document_number')
    op.drop_column('invoices', 'customer_document_type')
    op.drop_column('invoice_items', 'service_code')
    # ### end Alembic commands ###
