"""Add catalog tables (categories, services, price_history)

Revision ID: 65a649d3c724
Revises: 35fd5f137502
Create Date: 2025-11-22 23:25:34.193890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65a649d3c724'
down_revision: Union[str, None] = '35fd5f137502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_price_history_service_id', table_name='price_history')
    op.create_foreign_key(None, 'price_history', 'services', ['service_id'], ['id'])
    op.drop_index('ix_services_category_id', table_name='services')
    op.create_foreign_key(None, 'services', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.create_index('ix_services_category_id', 'services', ['category_id'], unique=False)
    op.drop_constraint(None, 'price_history', type_='foreignkey')
    op.create_index('ix_price_history_service_id', 'price_history', ['service_id'], unique=False)
    # ### end Alembic commands ###
