"""add_code_to_services_table

Revision ID: 6dcf529e091b
Revises: f7ebe50d7c5d
Create Date: 2025-12-09 09:36:58.427112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcf529e091b'
down_revision: Union[str, None] = 'f7ebe50d7c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('code', sa.String(length=20), nullable=True))
    
    # Populate existing rows with a default value
    op.execute("UPDATE services SET code = 'TEMP-' || id")
    
    # Alter the column to be non-nullable
    op.alter_column('services', 'code', nullable=False)
    
    op.create_index(op.f('ix_services_code'), 'services', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_code'), table_name='services')
    op.drop_column('services', 'code')
    # ### end Alembic commands ###
