"""Update order tables with foreign keys

Revision ID: f7ebe50d7c5d
Revises: 05c12c0c55ce
Create Date: 2025-11-23 03:19:44.333183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7ebe50d7c5d'
down_revision: Union[str, None] = '05c12c0c55ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
